#!/bin/bash

echo "💰 AFFILIATE PROGRAM SIGNUP GUIDE"
echo "================================="
echo ""
echo "🎯 PRIORITY ORDER (Start with these 3):"
echo ""

echo "1. 🥇 AMAZON ASSOCIATES (Easiest, 1-10% commission)"
echo "---------------------------------------------------"
echo "URL: https://affiliate-program.amazon.com"
echo "Steps:"
echo "  1. Sign up with your Amazon account"
echo "  2. Provide website: https://aitools.lovehappyhours.com"
echo "  3. Describe your site: 'AI tools reviews and recommendations'"
echo "  4. Wait 24-48 hours for approval"
echo "  5. Start adding Amazon links to your reviews"
echo "Commission: 1-10% depending on category"
echo ""

echo "2. 🥈 CLICKBANK (Digital products, 50-75% commission)"
echo "----------------------------------------------------"
echo "URL: https://www.clickbank.com"
echo "Steps:"
echo "  1. Create account"
echo "  2. Browse 'Software' category for AI tools"
echo "  3. Choose products with high gravity (popularity)"
echo "  4. Get affiliate links"
echo "  5. Add to your reviews"
echo "Commission: 50-75% (very high!)"
echo ""

echo "3. 🥉 DIRECT AI COMPANY PROGRAMS (Check each)"
echo "---------------------------------------------"
echo "• OpenAI (ChatGPT): https://openai.com/affiliate-program"
echo "• Anthropic (Claude): Check their website for affiliate info"
echo "• Midjourney: Check Discord #announcements"
echo "• GitHub Copilot: https://github.com/marketplace"
echo "• Notion: https://www.notion.so/affiliate"
echo ""

echo "📝 SIGNUP CHECKLIST:"
echo "□ Create professional email: affiliate@aitools.lovehappyhours.com"
echo "□ Prepare website description"
echo "□ Have tax information ready (SSN/EIN for US)"
echo "□ Set up PayPal for payments"
echo "□ Bookmark each affiliate dashboard"
echo ""

echo "⏰ TIME ESTIMATE:"
echo "- First 3 programs: 30-60 minutes"
echo "- Approval: 1-3 days (Amazon takes longest)"
echo "- Setup complete: 1 week"
echo ""

echo "🚀 ACTION PLAN FOR TODAY:"
echo "1. Sign up for Amazon Associates (15 minutes)"
echo "2. Sign up for ClickBank (10 minutes)"
echo "3. Check OpenAI/Anthropic affiliate programs (10 minutes)"
echo "4. Note your affiliate IDs"
echo ""

echo "📊 EXPECTED COMMISSIONS:"
echo "• Amazon: $5-50 per sale (electronics/software)"
echo "• ClickBank: $50-200 per sale (digital products)"
echo "• Direct AI: $20-100 per signup (recurring possible)"
echo ""

echo "💡 TIPS:"
echo "• Use the same email for all programs"
echo "• Track your links in a spreadsheet"
echo "• Start with Amazon (easiest approval)"
echo "• Focus on high-commission products first"
echo ""

echo "✅ Ready to start? Open the links above in your browser!"