#!/bin/bash

echo "🚀 DEPLOY AI TOOLS SITE NOW"
echo "==========================="
echo ""
echo "Your site is ready to deploy!"
echo ""
echo "Option A: Deploy to Netlify (Recommended)"
echo "----------------------------------------"
echo "1. Go to https://app.netlify.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New site from Git'"
echo "4. Select your repository"
echo "5. Deploy!"
echo ""
echo "Option B: Deploy to GitHub Pages"
echo "--------------------------------"
echo "1. Create GitHub repository"
echo "2. Push your code:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git remote add origin [your-repo-url]"
echo "   git push -u origin main"
echo "3. Go to Settings > Pages"
echo "4. Select 'Deploy from branch'"
echo "5. Choose 'main' branch"
echo ""
echo "Option C: Manual FTP Upload"
echo "---------------------------"
echo "1. Get FTP credentials from your host"
echo "2. Upload all files to public_html/"
echo "3. Visit your domain"
echo ""
echo "📋 FILES READY FOR DEPLOYMENT:"
echo "- index.html (Main page)"
echo "- content/reviews/ (5 review templates)"
echo "- scripts/ (Automation scripts)"
echo "- README.md (Project documentation)"
echo ""
echo "🔗 REPLACE AFFILIATE LINKS:"
echo "Before deploying, replace:"
echo "[YOUR_CHATGPT_AFFILIATE_LINK]"
echo "[YOUR_MIDJOURNEY_AFFILIATE_LINK]"
echo "[YOUR_CLAUDE_AFFILIATE_LINK]"
echo "[YOUR_COPILOT_AFFILIATE_LINK]"
echo ""
echo "📊 ANALYTICS SETUP:"
echo "1. Sign up for Google Analytics"
echo "2. Add tracking code to index.html"
echo "3. Set up conversion tracking"
echo ""
echo "🎯 QUICK DEPLOY COMMANDS:"
echo "# Initialize git (if not already)"
echo "cd /Users/chetantemkar/aitools-affiliate"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit'"
echo ""
echo "# Create GitHub repo and push"
echo "gh repo create aitools-affiliate --public --source=. --remote=origin --push"
echo ""
echo "⏰ Estimated deployment time: 15-30 minutes"
echo ""
echo "Need help with any step? Just ask!"