#!/bin/bash

echo "🔗 SETUP CUSTOM DOMAIN: aitools.lovehappyhours.com"
echo "=================================================="
echo ""

echo "Step 1: Add Custom Domain to GitHub Pages"
echo "-----------------------------------------"
echo "1. Go to: https://github.com/chetantemkar/aitools-affiliate/settings/pages"
echo "2. Under 'Custom domain', enter: aitools.lovehappyhours.com"
echo "3. Click Save"
echo ""

echo "Step 2: Update DNS Records"
echo "--------------------------"
echo "Go to your domain registrar (where you bought aitools.lovehappyhours.com)"
echo "Add these DNS records:"
echo ""
echo "Type    Name                     Value"
echo "----    ----                     -----"
echo "A       @                        185.199.108.153"
echo "A       @                        185.199.109.153"
echo "A       @                        185.199.110.153"
echo "A       @                        185.199.111.153"
echo "OR"
echo "CNAME   www                      chetantemkar.github.io"
echo ""
echo "Step 3: Wait for Propagation"
echo "---------------------------"
echo "DNS changes can take 1-24 hours to propagate."
echo "Check status: https://dnschecker.org"
echo ""
echo "Step 4: Enable HTTPS"
echo "-------------------"
echo "GitHub Pages will automatically issue an SSL certificate."
echo "This can take up to 24 hours after DNS propagates."
echo ""
echo "Step 5: Verify Setup"
echo "-------------------"
echo "After 24 hours, check:"
echo "1. https://aitools.lovehappyhours.com loads"
echo "2. SSL certificate is valid (padlock icon)"
echo "3. All pages work correctly"
echo ""
echo "📊 Quick Test Commands:"
echo "curl -I https://aitools.lovehappyhours.com"
echo "nslookup aitools.lovehappyhours.com"
echo ""
echo "🔄 Alternative: Use Netlify for Faster Setup"
echo "-------------------------------------------"
echo "If DNS is complicated, use Netlify instead:"
echo "1. Sign up at https://app.netlify.com"
echo "2. Import from GitHub"
echo "3. Netlify handles DNS and SSL automatically"
echo ""
echo "✅ Done! Your site will be live at https://aitools.lovehappyhours.com"