#!/bin/bash

echo "📧 CONVERTKIT SETUP - AI TOOLS AFFILIATE"
echo "========================================="
echo ""
echo "🎯 PURPOSE: Email list for affiliate programs, audience building"
echo "⏰ TIME NEEDED: 10 minutes"
echo "💰 COST: Free up to 1,000 subscribers"
echo ""

echo "📝 STEP 1: SIGN UP FOR CONVERTKIT"
echo "----------------------------------"
echo "1. Open: https://convertkit.com"
echo "2. Click 'Get Started Free'"
echo "3. Enter email: [YOUR EMAIL]"
echo "4. Create password"
echo "5. Verify email"
echo ""

echo "📝 STEP 2: CREATE ACCOUNT DETAILS"
echo "----------------------------------"
echo "Account name: AI Tools Affiliate"
echo "Website: https://ctemkar.github.io/aitools-affiliate/"
echo "Industry: Technology"
echo "Primary goal: Grow email list"
echo ""

echo "📝 STEP 3: CREATE SIGNUP FORM"
echo "------------------------------"
echo "1. Go to 'Forms' in left menu"
echo "2. Click 'Create new form'"
echo "3. Choose 'Inline form'"
echo "4. Form name: 'AI Tools Newsletter'"
echo "5. Headline: 'Get AI Tool Reviews & Tips'"
echo "6. Description: 'Weekly insights on ChatGPT, Midjourney, Claude & more'"
echo "7. Button text: 'Subscribe Free'"
echo "8. Success message: 'Thanks! Check your email for confirmation.'"
echo "9. Save form"
echo ""

echo "📝 STEP 4: GET EMBED CODE"
echo "--------------------------"
echo "1. Click 'Embed' on your form"
echo "2. Copy the JavaScript code"
echo "3. We'll add it to our website"
echo ""

echo "📝 STEP 5: CREATE WELCOME EMAIL"
echo "--------------------------------"
echo "1. Go to 'Broadcasts' → 'Sequences'"
echo "2. Create new sequence: 'Welcome Series'"
echo "3. Email 1 (Immediate):"
echo "   Subject: Welcome to AI Tools Affiliate!"
echo "   Content:"
echo "   Hi there,"
echo "   Thanks for subscribing! You'll get:"
echo "   • Weekly AI tool reviews"
echo "   • Practical AI tips"
echo "   • Affiliate opportunities"
echo "   First review: ChatGPT 2026 - still the best?"
echo "   [Link to review]"
echo "   Cheers,"
echo "   AI Tools Affiliate Team"
echo "4. Save sequence"
echo ""

echo "📝 STEP 6: CREATE LEAD MAGNET"
echo "------------------------------"
echo "1. Go to 'Landing Pages'"
echo "2. Create 'AI Tool Comparison Chart 2026'"
echo "3. Offer: Free PDF download"
echo "4. Require email for download"
echo "5. Design simple page with:"
echo "   • Comparison of 10+ AI tools"
echo "   • Features, pricing, best for"
echo "   • Download button"
echo ""

echo "📝 STEP 7: ADD TO OUR WEBSITE"
echo "------------------------------"
echo "1. Open index.html"
echo "2. Add form code to sidebar/footer"
echo "3. Test signup"
echo "4. Verify email delivery"
echo ""

echo "📝 STEP 8: INITIAL SUBSCRIBERS"
echo "-------------------------------"
echo "1. Add yourself as first subscriber"
echo "2. Add 5-10 friends/colleagues"
echo "3. Share on personal social media"
echo "4. Goal: 10+ subscribers first week"
echo ""

echo "🎯 DONE!"
echo "-------"
echo "✅ ConvertKit account created"
echo "✅ Signup form ready"
echo "✅ Welcome email set up"
echo "✅ Lead magnet created"
echo "✅ Form added to website"
echo "✅ Initial subscribers added"
echo ""
echo "📊 NEXT: Monitor email opens/clicks"
echo "⏰ TIME SPENT: ~10 minutes"
echo ""
echo "🔗 Quick links:"
echo "- Dashboard: https://app.convertkit.com/"
echo "- Forms: https://app.convertkit.com/forms"
echo "- Subscribers: https://app.convertkit.com/subscribers"
echo "- Analytics: https://app.convertkit.com/analytics"