#!/bin/bash

echo "📝 AI TOOL REVIEW WRITING ASSISTANT"
echo "==================================="
echo ""
echo "Available review templates:"
echo "1. ChatGPT-review-complete.md (DONE - 3613 words)"
echo "2. ChatGPT-review.md (Template)"
echo "3. Midjourney-review.md (Template)"
echo "4. Claude-review.md (Template)"
echo "5. GitHub-Copilot-review.md (Template)"
echo "6. Notion-AI-review.md (Template)"
echo ""

echo "🎯 QUICK START:"
echo "Pick one template and fill it in:"
echo ""
echo "cd /Users/chetantemkar/aitools-affiliate/content/reviews/"
echo "cp ChatGPT-review.md MyTool-review.md"
echo "nano MyTool-review.md"
echo ""
echo "📋 REVIEW STRUCTURE:"
echo "1. Tool name and rating"
echo "2. Quick summary"
echo "3. Key features (5-10 points)"
echo "4. Pros & cons"
echo "5. Pricing comparison"
echo "6. How it compares to alternatives"
echo "7. Getting started guide"
echo "8. Tips for success"
echo "9. Final verdict"
echo "10. Affiliate link"
echo ""
echo "⏰ TIME ESTIMATES:"
echo "- Basic review: 30-60 minutes"
echo "- Detailed review: 2-3 hours"
echo "- Complete with testing: 4-8 hours"
echo ""
echo "🚀 TODAY'S GOAL:"
echo "Complete 1 review (pick ChatGPT, Midjourney, or Claude)"
echo ""
echo "💡 TIPS:"
echo "• Test the tool yourself if possible"
echo "• Include screenshots"
echo "• Be honest about pros and cons"
echo "• Update pricing information"
echo "• Add personal experience"
echo ""
echo "📊 WORD COUNT TARGETS:"
echo "- Minimum: 1000 words"
echo "- Good: 2000 words"
echo "- Excellent: 3000+ words"
echo ""
echo "✅ Ready to write? Pick a template and start!"